---
- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ dir_project }}'
    - '{{ dir_project_environment }}'
    - '{{ dir_project_environment_versions }}'

- name: Get list of versions
  find:
    paths: '{{ dir_project_environment_versions }}'
    file_type: directory
  register: versions

- name: Create next version directory
  file:
    path: '{{ dir_next_version }}'
    state: directory

- name: Deploy artifact
  unarchive:
    src: '{{ node_archive }}'
    dest: '{{ dir_next_version }}'
    extra_opts: [--strip-components=1]
  notify:
    - restart service

- name: Install project requirements
  npm:
    state: present
    production: True
    path: '{{ dir_next_version }}'

- name: Point symlink to next version
  file:
    src: '{{ dir_next_version }}'
    dest: '{{ link_current }}'
    state: link
  notify: restart service
