---
- name: Read package.json
  include_vars:
      file: package.json
      name: package

- name: Set project name
  set_fact:
    node_project_name: '{{ package.name }}'
  when: not node_project_name

- name: Set project version
  set_fact:
    node_version: '{{ package.version }}'
  when: not node_version

- name: Set project id
  set_fact:
    node_project_id: '{{ node_project_name }}'
  when: not node_project_id

- name: Make project id environment safe
  set_fact:
    node_project_id: 'node-{{ node_project_id }}-{{ node_project_environment }}'

- name: Verify port is defined
  fail:
    msg: You must define port
  when: not node_project_port

- name: Verify server name is defined
  fail:
    msg: You must define at least one server name
  when: not node_server_name

- name: Verify project version is defined
  fail:
    msg: You must define project version
  when: not node_version

- name: Verify project environment is defined
  fail:
    msg: You must define project environment
  when: not node_project_environment


- name: Configure directories
  set_fact:
    dir_project: '{{ node_projects_directory }}/{{ node_project_name }}'
    dir_project_environment: '{{ node_projects_directory }}/{{ node_project_name }}/{{ node_project_environment }}'
    dir_ssl_certificate: '/etc/letsencrypt/live/{{ node_server_name.split(" ")[0] }}'

- name: Configure paths
  set_fact:
    dir_next_version: '{{ dir_project_environment }}/versions/{{ node_version }}'
    dir_project_environment_modules: '{{ dir_project_environment }}/node_modules'
    dir_project_environment_versions: '{{ dir_project_environment }}/versions'
    link_current: '{{ dir_project_environment }}/current'
    node_static_dir: '{{ dir_project_environment }}/current/static'
    node_ssl_certificate_path: '{{ dir_ssl_certificate }}/fullchain.pem'
    node_ssl_certificate_key_path: '{{ dir_ssl_certificate }}/privkey.pem'
    node_systemd_service_file: '{{ node_systemd_dir }}/{{ node_project_id }}.service'

- name: Guess archive location
  set_fact:
    node_archive: '{{ node_project_name }}-{{ node_version }}.tgz'
  when: not node_archive

  changed_when: True
  notify:
    - start nginx
    - start service

- include_tasks: deps.yml
- include_tasks: deploy.yml
- include_tasks: config.yml
